# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Son Build Me A House Church Resources
email: sonbuildmeahouse@helix.vision
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll


#these are the configuration variables for git-wiki
show_downloads: true
comments: true
git_branch: master
logo_url:
google_analytics:
theme:
wiki_folder: wiki
use_github_wiki: false
use_prose_io: true
google_cse_token:
custom_head: false
custom_sidebar: true
custom_footer: false

include:
  - "_pages"
exclude:
  - "/assets/"
  - "/bower_components/"
  - "bower.json"
  - "gulpfile.js"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpconfig.yml"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
